<?php
$modversion['name'] = _VL_WEATHER_NAME;
$modversion['version'] = "0.9";
$modversion['description'] = _VL_WEATHER_DESC;
$modversion['credits'] = "Derived from the code of PHP-Weather and XP-Weather";
$modversion['author'] = "Nicholas Petreley";
$modversion['help'] = "vlweather_help.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = "0";
$modversion['image'] = "vlweather.jpg";
$modversion['dirname'] = "vlweather";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/vlweather.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "metars";
$modversion['tables'][1] = "vlwusers";
$modversion['tables'][2] = "stations";
$modversion['tables'][3] = "pmetars";

// Menu
$modversion['hasMain'] = 1;

// Templates
//$modversion['templates'][1]['file'] = 'vlweatherblock.html';
//$modversion['templates'][1]['description'] = '';

// block
$modversion['blocks'][1]['file'] = "vlweatherblock.php";
$modversion['blocks'][1]['name'] = "Weather";
$modversion['blocks'][1]['description'] = "VL Weather";
$modversion['blocks'][1]['show_func'] = "b_vlweather";
$modversion['blocks'][1]['edit_func'] = "b_edit_vlweather";
$modversion['blocks'][1]['options'] = "KSFO|both_imperial";
$modversion['blocks'][1]['template'] = 'vlweatherblock.html';
?>
